<h2>A Könyvtár története</h2>
<p>Békés város könyves és könyvtári múltjából 1840-ig kevés adat áll rendelkezésünkre. A helytörténeti források jelentősebb gyűjteményként említik Szegedi Kis Istvánnak reformátor 200 kötetes könyvtárát 1552-ből, valamint a református gimnázium 300 kötetes tanári és 80 kötetes ifjúsági könyvtárát 1865-ből.</p>

<p>A XIX. században a felvilágosodás eszmeiségének folytatásaként, a reformkor szellemének megfelelően egyre több társadalmi mozgalom tűzte ki céljául nyilvános közkönyvtár alapítását. Ehhez kedvező környezetet teremtett a politikai viszonyok változása, a cenzúra enyhülése, a könyvkiadói könyvkereskedelmi tevékenység fejlődése. A harmincas negyvenes években sok vidéki településen alakult olvasóegylet, olvasókör, kaszinó.</p>

<p>Az olvasókör társadalmi kezdeményezést, civil szerveződést jelentett, amelynek elsődleges célja az olvasás, a színvonalas művelődés elősegítése, terjesztése volt. Az egyleteknek fontos szerepük volt az elmaradott területek szellemi és gazdasági felzárkóztatásában, a vidéki emberek számára egyetlen művelődési, tájékozódási és szórakozási lehetőséget jelentették. Az általában 100-250 kötettel rendelkező körökben könyvkölcsönzés, újságolvasás, felolvasás és rádióhallgatás folyt. Egy-egy kör általában az azonos társadalmi helyzetű, vallási és politikai nézetű embereket fogta össze. Az olvasás mellett az együttes beszélgetések, tevékenységek formálták az érdeklődők nézeteit. A legtöbb kör haladó, reform eszméket képviselt. 1879-ben hivatalosan 37 békés megyei olvasókört tartottak nyilván, amelyből nyolc Békésen működött. Az engedélyezett olvasókörök mellett említésre méltóak a zugolvasókörök, amelyek a szegényebb néposztálynak nyújtottak művelődési, tájékozódási lehetőséget. A zugegyletek általában az egymás közelében lakók között szerveződtek. Fő tevékenységük az olvasás és kölcsönzés mellett a mindennapi eszmecsere, politikai tájékozódás, termelési munkavállalási problémák megbeszélése. A zugolvasókörök száma 10-20 között mozgott a 19. század végén. A legelső békési olvasókör Hajnal Ábel professzor kezdeményezésére 1840-ben alakult a Békési Olvasótársaság, későbbi nevén Polgári Kaszinó. Ennek az olvasókörnek volt a legtöbb könyve, szám szerint 2347. Békésben és kerületeiben, tanyáin még sok olvasókör rendelkezett 150-200 kötettel, valamint említésre méltó egyes magánszemélyek 800-1000 kötetes magánkönyvtára. A XIX. század második felétől az olvasás megszerettetéséért és a kultúra, a műveltség emeléséért a legtöbbet az olvasókörök tették.</p>

<p>Már a kiegyezés utáni időkben a társadalmi kezdeményezésekkel párhuzamosan megfogalmazódott a politikusokban az igény, hogy a szegényebb néprétegek műveltségének emelését intézményes formában kellene megvalósítani. A kevés iskolát végzett vidéki települések, falvak lakosainak könyvekkel való ellátását a népkönyvtárak létrehozásával látták biztosítottnak. A könyvtárügy irányítása ebben az időszakban a Vallási és Közoktatási Minisztérium feladata lett volna, de tevékenyen csak az általa támogatott közművelődési egyesületek foglalkoztak a témával.</p>

<p>Gyulán, az akkori megyeszékhelyen 1895-ben alakult meg a Békésvármegyei Közművelődési Egyesület. Békés megyében az első népkönyvtári mozgalom elindítása az ő nevükhöz fűződik. 1899. februárjában a vármegye 34 településén összesen 7204 kötettel alapítottak népkönyvtárakat. A megvalósulást a földművelésügyi miniszter államsegélye tette lehetővé. Békésen 632 kötettel alakult meg a népkönyvtár, felügyeletét a helyi bizottság látta el. A könyvtár iskolai tanteremben működött, tevékenysége kb. négy évig követhető nyomon a ma rendelkezésünkre álló források alapján. A népkönyvtárakat később a földművelésügyi minisztérium vette át. Az 1890-es évek végén a békésieknek lehetőségük volt arra is, hogy pénzért kölcsönözzenek könyvet: Véver Oszkár könyvkereskedő 600 kötetből álló kölcsönkönyvtárát reklámozza, ajánlja az Alföldi Híradó c. lapban.</p>

<p>A békési könyvtár jogelődjét, a békési népkönyvtárat a kultúrotthonnal együtt hivatalosan 1949. november 27-én avatták fel. Az első falusi kultúrotthon felavatása országos jelentőségű esemény volt. Békés község kultúrotthonának felavatásával kezdődött el az állami és társadalmi szervek összefogásával indított mozgalom, amely a művelődési házak és a könyvtárak hálózatának kiépítését tűzte ki célul. A bérházban kialakított kultúrotthont és könyvtárat Losonczy Géza, a Népművelési Minisztérium államtitkára avatta fel. Az avatás alkalmával a könyvtár 1000 új szépirodalmi és szakkönyvet kapott ajándékba a Népművelési Minisztériumtól. A békési népkönyvtár szervezése már a hivatalos átadás előtt februárban megkezdődött. A szervezési feladatokkal P. Szász Lajos tanítót bízták meg. A népkönyvtár állományát a Polgári Kaszinó és egyéb olvasókörök, valamint a bérházban működő ifjúsági szervezet könyveiből alakították ki. A könyvtár a kultúrház emeleti helyiségeiben működött, tiszteletdíjas könyvtáros látta el a könyvtári teendőket, hetente két alkalommal volt kölcsönzés. Felolvasó esteket eleinte magánházaknál tartottak, később író-olvasó találkozókat, előadói esteket is szerveztek a művelődési házzal együtt. A népkönyvtár felügyeletét 1952-ig a békéscsabai népkönyvtár látta el: szakmai tanácsadással és letéti könyvanyaggal segítette a munkát. 1953-tól, a Békés Megyei Könyvtár megalakulásától a békési népkönyvtár önállóvá vált. 1955-től községi könyvtárként működött. Javultak a működési feltételek: a tiszteletdíjas könyvtárost főállású váltotta fel, heti hat napra nőtt a nyitva tartási idő.</p>

<p>A népkönyvtár 1959-től járási könyvtár, ez azonban minőségi változást nem jelentett a könyvtár életében: továbbra is a szűkös emeleti 26 m²-es he1yiségekben üzemelt. 1962. március 1-jén költözött a 130 m²-es könyvtári célra kialakított földszinti területre. 1963-ban alakították ki a 30 m²-es gyermekrészleget, amelyet 1964-ben ismét 40 m²-rel sikerült bővíteni. 1973-ban Békés negyedik alkalommal kapta meg a városi rangot. Ez évtől a könyvtár Járási-városi Könyvtárként, majd a járások megszűnése után Városi Könyvtár néven működött. A következő nagy átalakításra és korszerűsítésre a megye könyvtárfejlesztési programjának keretében került sor. A munkálatok idején a könyvtár a járásbíróság épületében üzemelt. Az alapterület 274 m2-re bővült. A felújított könyvtárat 1977. november 25-én adták át. A könyvtár átalakítása Lipták Pál tervei alapján készült. Alapkövetelménye volt a szakmaiság mellett, hogy a könyvtár belső építészetileg tágas, esztétikus és otthonos legyen. A felújított könyvtár minden tekintetben megfelelt a kor elvárásainak: a szakszerűen kialakított kölcsönző, olvasó és zenei részleg kiválóan alkalmas volt a korszerű könyvtári ellátásra. 1978-as földrengés megrongálta a műemlék jellegű épületet, ezért ismét a járásbíróság épületébe költözött a könyvtár. 1979. március 21-én költözött vissza a helyre állított épületbe.</p>

<p>1981. augusztus 17-én avatták a gyerekek új 230 m²-es birodalmát. Az átalakított olvasói terek hosszú évekig biztosították a színvonalas kiszolgálást. Az évek során kisebb-nagyobb technikai-műszaki fejlesztést hajtottak végre az intézményen. Az állomány folyamatosan gyarapodott, már nemcsak könyvekkel, hanem folyóiratokkal, hanglemezekkel is gazdagodott. A 90-es évek társadalmi-politikai változásai, az informatika gyors ugrásszerű fejlődése, a belső terek és a bútorok elhasználódása, a zsúfoltság, a megváltozott olvasói igények miatt ismét korszerűsíteni kellett az intézményt. Az önkormányzat 2000-ben hozott határozatot a könyvtár felújításáról, bővítéséről. A gyermekkönyvtárat az épület használaton kívüli helyiségeiben alakították ki. A gyerekek 2002-ben vették birtokukba a gyerekbarát, jól felszerelt, hangulatos gyerekkönyvtárat. A könyveken kívül folyóiratok, elektronikus dokumentumok és az internet-használat is a rendelkezésükre áll.</p>

<p>2002. őszén kezdődött a felnőtt könyvtár átalakítása. A terület nagysága lehetővé tette, hogy a kölcsönző részleg és az olvasóterem külön- külön működjön a továbbiakban. Szabadpolcon kétszer annyi kölcsönözhető könyvet tudtunk elhelyezni, mint előzőleg. Az olvasóterem kialakításánál az volt a cél, hogy esztétikailag és a funkció szempontjából is megfeleljen az elvárásoknak. Fontos szempont volt, hogy az olvasó kellemesen érezze magát, el tudjon igazodni a szolgáltató helyeken, valamint lehetőség legyen az elmélyült munkára is. A különböző részlegek egy légtérben, de elkülönült egységként működnek: tájékoztatás, folyóirat-olvasó, zenei részleg, internet- és számítógép-használat, Európai Uniós információk, helyismeret. Jelenleg 76 000-nél több dokumentummal rendelkezünk könyv, folyóiratok, irodalmi és zenei lemezek, elektronikus dokumentumok formájában.</p>

<p>Jövőbeli fő célunk az, hogy a békési könyvtár is biztosítson épülettől és nyitva tartási időtől függetlenül hozzáférést az információkhoz, adatokhoz, könyvtári szolgáltatások jelentős részéhez. A megvalósításhoz könyvtári portál kialakítása szükséges. A portál az egységes regisztrációs rendszer segítségével „kaput” jelent az összes elérhető szolgáltatáshoz, nemcsak a békési, hanem a magyarországi könyvtári hálózat egészére nézve.</p>
