<table>
    <caption><br>TÁBLÁZAT</caption>
    <tr>
        <th>teszt1</th>
        <th>teszt2</th>
        <th>teszt3</th>
        <th>teszt4</th>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
